#Basic
locale                   : "th-TH"
title                    : "Ruangrit Srimuang"
title_separaton          : "-"
name                     : &name "Ruangrit Srimuang" 
description              : &description "personal description"
url                      : https://academicpages.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "/ruangritworks/portfolio"